### ISSUE TITLE
CI: Various optimizations

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#164]
Thanks to Bret, we are pushing the best practices
https://github.com/BretFisher/allhands22/tree/main/.github/workflows

**Comment by pascalandy** [comment]
- https://github.com/firepress-org/ghostfire/pull/165
- 0o0o

**Comment by pascalandy** [comment]
Need to add docker meta

```
      - name: Docker Metadata for Final Image Build
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: bretfisher/allhands22,ghcr.io/bretfisher/allhands22
          flavor: |
            latest=false
          tags: |
            type=raw,value=99
          # comment these out on all but 04-add-metadata.yaml to avoid overwriting image tags
          # type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          # type=ref,event=pr
          # type=ref,event=branch
          # type=semver,pattern={{version}}
```

**Comment by pascalandy** [comment]
Avoid pushing CI image to docker thanks to 'load'

```
#NEW: (START) ##########################################################
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          target: test
```
