### ISSUE TITLE
Docker Meta

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#174]
if needed in the future

In this example, we push to dockerhub + ghcr

```
  - name: Docker Metadata for Final Image Build
    id: docker_meta
    uses: docker/metadata-action@v3
    with:
      images: bretfisher/allhands22,ghcr.io/bretfisher/allhands22
      flavor: |
        latest=false
      tags: |
        type=raw,value=99
      # comment these out on all but 04-add-metadata.yaml to avoid overwriting image tags
      # type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
      # type=ref,event=pr
      # type=ref,event=branch
      # type=semver,pattern={{version}}
```
