### ISSUE TITLE
CI: Stop pushing CI test image. Use Docker Engine instead

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#176]
This will remove the ci-version tag from our CICD. 

Avoid pushing CI image to docker thanks to 'load'

```
#NEW: (START) ##########################################################
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          target: test
```

https://github.com/BretFisher/allhands22/tree/main/.github/workflows
