### ISSUE TITLE
GitHub Actions: new set of environment files

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#358]
Impact on the CD-CD yaml file

> To avoid untrusted logged data to use save-state and set-output workflow commands without the intention of the workflow author we have introduced a [new set of environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) to manage state and output.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by pascalandy** [comment]
## Example of writing an environment variable to GITHUB_ENV

```
steps:
  - name: Set the value
    id: step_one
    run: |
      echo "action_state=yellow" >> "$GITHUB_ENV"
  - name: Use the value
    id: step_two
    run: |

      echo "${{ env.action_state }}" # This will output 'yellow'

```
