### ISSUE TITLE
Checkpoint: Add snyk

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#54]
example

```
      - 
        name: Run Snyk to check Docker image for vulnerabilities
        # https://github.com/snyk/actions/tree/master/docker
        uses: snyk/actions/docker@0.3.0
        # Snyk can be used to break the build when it detects vulnerabilities.
        # In this case we want to upload the issues to GitHub Code Scanning
        continue-on-error: true
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: bretfisher/docker-github-actions-example
          args: --file=Dockerfile --severity-threshold=high
      - 
        name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
```

[source](https://github.com/BretFisher/docker-github-actions-example/blob/main/.github/workflows/docker-build-and-push.yml#L97)
