### ISSUE TITLE
on pause: Deploy to stable instance

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#587]
I removed this step: `Deploy to stable instance`

```yml
  cd_stable:
    needs: [build_stable]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: zcong1993/setup-timezone@v2.0.0
        with:
          timezone: America/Montreal

      - name: Deploy to stable instance
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.NODE1 }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY_ACTIONS }}
          passphrase: ${{ secrets.SSH_KEY_ACTIONS_PASSPHRASE }}
          script: |
            ${{ secrets.SSH_CMD__UPDATE_DKR_IMG_STABLE }}
            hostname
```
