### ISSUE TITLE
github actions/ release

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#59]
This would be useful to release themes.
```
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*.tar.gz
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

- https://github.com/softprops/action-gh-release
- idea: https://github.com/crazy-max/diun/blob/master/.github/workflows/build.yml#L145
