### ISSUE TITLE
CI: review_cache_size / path not found

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#62]
I don't know where the cache dir is located. I would like to check this for due diligences and better optz.

This is returning an error:
`du -hs ${GITHUB_WORKSPACE}/tmp/.buildx-cache`

```
  # cache limit https://github.com/marketplace/actions/cache#cache-limits
  review_cache_size:
    needs: [myvars, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: zcong1993/setup-timezone@v1.1.1
        with:
          timezone: America/Montreal
      - name: Checkpoint | Github Actions cache size
        continue-on-error: true
        run: |
          du -hs ${GITHUB_WORKSPACE}/tmp/.buildx-cache
```
