### ISSUE TITLE
dependabot for dockerfile

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#66]
```
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
```
