### ISSUE TITLE
using reusable workflows

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#67]
## example for super-linter

```
---
name: Lint Code Base

on:
  push:
    branches: [master,edge]
  pull_request:

jobs:
  call-super-linter:
    uses: firepress-org/reusable_workflows/.github/workflows/super-linter.yaml@master
```

## docs
https://github.com/github/roadmap/issues/98
